name: SonarQube Analysis
on:
  push:
    branches:
      - main
      - 'pr-*-before-improvements'  # Your PR branches
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarQube analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6  # Match Spring Security's version
          cache-read-only: false

      - name: Execute SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for PR analysis
        run: |
          echo "=== STARTING ANALYSIS WITH FULL DEBUG ==="
          ./gradlew clean sonarqube \
            --stacktrace \
            --info \
            --scan \
            -Dsonar.verbose=true \
            -Dorg.gradle.debug=true
          
          echo "=== ANALYSIS COMPLETE ==="
          echo "Check logs above for errors"
          echo "Look for Build Scan URL in output"
